name: PokeBuilder-PostgreSQL

services:
  postgres:
    image: postgres:16
    container_name: pokebuilder-postgres
    restart: always
    environment:
      POSTGRES_DB: pokebuilder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokebuilder-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: pokebuilder
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: